export enum LlmErrorCode {
  INVALID_API_KEY = 'INVALID_API_KEY',
  EXPIRED_API_KEY = 'EXPIRED_API_KEY',
  QUOTA_EXCEEDED = 'QUOTA_EXCEEDED',
  INVALID_MODEL = 'INVALID_MODEL',
  RATE_LIMITED = 'RATE_LIMITED',
  CONTEXT_WINDOW_EXCEEDED = 'CONTEXT_WINDOW_EXCEEDED',
  PROVIDER_UNAVAILABLE = 'PROVIDER_UNAVAILABLE',
  NETWORK_ERROR = 'NETWORK_ERROR',
  INTERNAL_PROVIDER_ERROR = 'INTERNAL_PROVIDER_ERROR',
  UNKNOWN = 'UNKNOWN',
}
