export const REPOSITORY_ANALYSIS_CONSTANTS = {
  LANGUAGES: {
    TypeScript: ["tsconfig.json", "*.ts", "*.tsx"],
    JavaScript: ["*.js", "*.jsx"],
    Python: ["requirements.txt", "Pipfile", "pyproject.toml", "*.py"],
    Go: ["go.mod", "*.go"],
    Rust: ["Cargo.toml", "*.rs"],
    Java: ["pom.xml", "build.gradle", "*.java"],
    "C#": ["*.csproj", "*.sln", "*.cs"],
    PHP: ["composer.json", "*.php"],
  },
  FRAMEWORKS: [
    { name: "NestJS", packages: ["@nestjs/core"] },
    { name: "Next.js", packages: ["next"] },
    { name: "React", packages: ["react"] },
    { name: "Vue", packages: ["vue"] },
    { name: "Angular", packages: ["@angular/core"] },
    { name: "Express", packages: ["express"] },
    { name: "Fastify", packages: ["fastify"] },
    { name: "Django", files: ["manage.py"] },
    { name: "Flask", packages: ["flask"] },
    { name: "Spring", files: ["pom.xml", "build.gradle"] }, // Basic heuristic
  ],
  PACKAGE_MANAGERS: [
    { name: "pnpm", lockfile: "pnpm-lock.yaml" },
    { name: "npm", lockfile: "package-lock.json" },
    { name: "yarn", lockfile: "yarn.lock" },
    { name: "bun", lockfile: "bun.lockb" },
  ],
  BUILD_TOOLS: [
    { name: "Vite", packages: ["vite"] },
    { name: "Webpack", packages: ["webpack"] },
    { name: "Rollup", packages: ["rollup"] },
    { name: "esbuild", packages: ["esbuild"] },
    { name: "SWC", packages: ["@swc/core"] },
    { name: "Turbo", packages: ["turbo"] },
  ],
  TEST_FRAMEWORKS: [
    { name: "Jest", packages: ["jest"] },
    { name: "Vitest", packages: ["vitest"] },
    { name: "Playwright", packages: ["@playwright/test"] },
    { name: "Cypress", packages: ["cypress"] },
    { name: "Mocha", packages: ["mocha"] },
  ],
  MONOREPO_CONFIGS: [
    { name: "pnpm-workspace", file: "pnpm-workspace.yaml" },
    { name: "turbo", file: "turbo.json" },
    { name: "nx", file: "nx.json" },
    { name: "lerna", file: "lerna.json" },
  ],
  DOCKER_FILES: [
    "Dockerfile",
    "docker-compose.yml",
    "docker-compose.yaml",
    "compose.yaml",
  ],
  CI_CD_DIRECTORIES: [
    ".github/workflows",
    ".gitlab-ci.yml",
    ".circleci",
    "azure-pipelines.yml",
  ],
  DOCUMENTATION_PATTERNS: [
    "README.md",
    "README",
    "docs",
    "architecture",
    "api",
    "adr",
    "wiki",
  ],
  ENVIRONMENT_FILES: [".env", ".env.example", ".env.local"],
  API_SPECIFICATIONS: [
    "openapi.yaml",
    "openapi.yml",
    "openapi.json",
    "swagger.yaml",
    "swagger.json",
  ],
  WORKSPACE_FOLDERS: ["apps", "packages", "libs", "services"],
};
