import { Injectable } from "@nestjs/common";
import type { WorkflowState } from "@/domain/workflow";

@Injectable()
export class PullRequestTemplateService {
  /**
   * Generates the standard conventional commit Pull Request title.
   */
  generateTitle(state: WorkflowState): string {
    const runId = state.runId || "automated";
    return `docs(docpulse): update automated documentation [${runId}]`;
  }

  /**
   * Generates formatted markdown body for the Pull Request.
   */
  generateBody(state: WorkflowState): string {
    const runId = state.runId || "N/A";
    const repoName = state.repository?.name || "Repository";
    const score = state.criticReview?.score ?? "N/A";
    const approvedCount = state.criticReview?.approvedCount ?? 0;
    const totalDocs =
      state.criticReview?.totalDocuments ??
      (state.generatedDocuments?.length || 0);

    let docTableRows = "";
    if (state.generatedDocuments && state.generatedDocuments.length > 0) {
      for (const doc of state.generatedDocuments) {
        docTableRows += `| \`${doc.path}\` | ${doc.summary || "AI-generated documentation"} |\n`;
      }
    } else {
      docTableRows = "| N/A | No documentation generated |\n";
    }

    return `## 🤖 Automated Documentation Update

This Pull Request was automatically generated by **DocPulse AI Agentic Engine** following a thorough codebase analysis and multi-agent peer review loop.

---

### 📊 Quality & Review Summary

| Metric | Value |
| :--- | :--- |
| **Critic Overall Quality Score** | **${score}/100** |
| **Documents Approved** | ${approvedCount} of ${totalDocs} |
| **Target Repository** | \`${repoName}\` |
| **Workflow Run ID** | \`${runId}\` |

---

### 📚 Generated & Updated Documents

| Document Path | Summary |
| :--- | :--- |
${docTableRows}

---

### 🛡️ Verification & Safeguards

- [x] **Repository Analysis**: Analyzed architecture, dependencies, and code AST.
- [x] **Technical Writer**: Synthesized localized markdown guides.
- [x] **Documentation Critic**: Evaluated against 10 strict quality criteria (Accuracy, Clarity, Completeness, Actionability).
- [x] **Git Safe Commit**: Validated clean working tree and fast-forward branch compatibility.

*Generated by [DocPulse AI](https://github.com/docpulse)*`;
  }
}
